### ISSUE TITLE
MS-DIAL crushes for unknown reason - Windows

### ISSUE THREAD

**Issue by olgafccps** [systemsomicslab/MsdialWorkbench#119] opened 2023-06-20 14:27 UTC
Hi!
It seems we need some help with MS-DIAL software, Windows version. 
The attached file is a screenshot from version 5.1.230517 and when we press the "Next" button on that screen the program thinks for some seconds then closes without any error messages. We also have tried version 4.9.221218 but the effect was similar. The computer where it all happens has 32 Gb RAM, last generation of i7 CPU, lots of free disk space and Win10 Pro.  Turning off the antivirus software does not help. 
My colleague runs the software successfully on a similar computer. Can you suggest any ways to solve the problem?

Thank you in advanced!
![photo_msdial](https://github.com/systemsomicslab/MsdialWorkbench/assets/137190838/7f353a73-b705-43ad-b970-50f2b6b4d27b)

**Comment by kozo2** [comment] 2023-07-26 03:01
Hi @olgafccps ,
We recently uploaded a new version `5.1.230719` to http://prime.psc.riken.jp/compms/msdial/main.html . Can you tell me if your problem is reproduced with `5.1.230719`?

**Comment by kozo2** [comment] 2023-08-24 03:29
Hi @olgafccps Since I haven't received a response for a while, I will temporarily close this issue. If the problem persists, please feel free to reopen it.

**Closed by kozo2** 2023-08-24 03:29 UTC

**Comment by arpita-007** [comment] 2024-02-03 14:44
Hi,
I am facing the similar issue. I uploaded 80 files and when I start the alignment, after 62-69/80 it gets closed without showing any error. I am using the 5.1.230912 version on 64 GB system with 12 cores.
Thank you in advance!

**Comment by arpita-007** [comment] 2024-02-03 14:45
> Hi @olgafccps Since I haven't received a response for a while, I will temporarily close this issue. If the problem persists, please feel free to reopen it.

Hi @kozo2 ,
I am facing the similar issue. I uploaded 80 files and when I start the alignment, after 62-69/80 it gets closed without showing any error. I am using the 5.1.230912 version on 64 GB system with 12 cores.
Thank you in advance!
